# Generated by Django 3.2.3 on 2021-06-26 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20210516_1452'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='alt_tag_banner',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='alt_tag_thumbnail',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
